---
# tasks file for webserver
- name: install httpd package
  yum:
    name: 
      - httpd
      - firewalld
    state: present
- name: start service httpd
  service:
    name: httpd
    state: started
    enabled: yes
- name: start service firewalld
  service:
    name: firewalld
    state: started
    enabled: yes
- name: firewall rule
  firewalld:
    service: http
    state: enabled
    permanent: true
    immediate: yes
